### PR TITLE
add location's parameter and fix some comment.

### PR DESCRIPTION
**Pull request by leeonix**
i don't like your location `vs-premake5`, this is hard code.
because i write this premake5.lua can generate gnu makefile for gcc
you may use `premake5 gmake` to generate makefile and test it.

if you need more other location, i add a option `/to=` or `--to=`.
premake easy add it. i copy from premake's code,

usage:
`
    premake5 /to=vs2010 vs2010
`
or:
`
    premake5 --to=vs2012 vs2012
`
or:
`
    premake5 /to=build/gmake.windows /os=windows gmake
`
or:
`
    premake5 /to=build/gmake.linux /os=linux gmake
`

I add configmap for your configuration `ReleaseKjk`, in `dependlib` project, premake can not generate no use code.

### CODE REVIEW

**Comment by leeonix** [comment]
btw: I write a python script to generate a premake template file:[genpremake.py](https://gist.github.com/leeonix/4155c44597e3c211d2d8). it is simple.

**Comment by kjk** [comment]
Thanks. I've updated premake5.lua based on this but not by merging because I don't want to bring unnecessary merge checkins into history.

**Comment by leeonix** [comment]
OK. you should be check it out.
the github generate pr, add my merge commit from your source.
I don't know what's going on.

**Comment by kjk** [comment]
This is how git works. You used `git merge` to merge changes from my master to your master and added a commit on top of that. Now it's in your history so if I were to merge it back, those commits have to be merged too.

You could have avoided this by doing `git rebase` (although at this point it's too late).

The usual way when working on github is to keep master an exact copy of forked repo and do changes on branches.

At this point the easiest way to resync is to delete the repo and re-fork it.

**Comment by leeonix** [comment]
thx your hint.
But, I'm lazy. ^_^
some guy tell me, if your repository is not merge from trunk for a long time.
use github to create a pull request. use mouse click, one two three, done!
using github pull request, it is remote operation.

**Pull request closed without merging**
